### ISSUE TITLE
Support stable Rust

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc82x-hal#11]
This crate currently requires a nightly Rust toolchain. We currently use the following experimental features:
- [ ] `const_fn` ([documentation](https://doc.rust-lang.org/nightly/unstable-book/language-features/const-fn.html), [tracking issue](https://github.com/rust-lang/rust/issues/24111))
- [x] ~`const_refcell_new` ([~documentation~](https://doc.rust-lang.org/nightly/unstable-book/library-features/const-refcell-new.html), [tracking issue](https://github.com/rust-lang/rust/issues/24111))~
- [x] ~`macro_reexport` ([~documentation~](https://doc.rust-lang.org/nightly/unstable-book/language-features/macro-reexport.html), [tracking issue](https://github.com/rust-lang/rust/issues/29638))~
- [ ] `never_type` ([documentation](https://doc.rust-lang.org/nightly/unstable-book/language-features/never-type.html), [tracking issue](https://github.com/rust-lang/rust/issues/35121))
- [x] ~`use_extern_macros` ([documentation](https://doc.rust-lang.org/nightly/unstable-book/language-features/use-extern-macros.html), [tracking issue](https://github.com/rust-lang/rust/issues/35896))~

It think supporting stable Rust would be nice, but I don't see this as a pressing issue. It's probably best to just wait for the various experimental features to stabilize and re-evaluate then.

**Comment by hannobraun** [comment]
Updated the original comment. `macro_reexport` has been replaced with `use_extern_macros`.

**Comment by hannobraun** [comment]
Update original comment. As of #85, `const_refcell_new` and `use_extern_macros` are no longer used and all dependencies build on beta.

**Comment by hannobraun** [comment]
Parts of `const fn` have been stabilized: https://github.com/rust-lang/rust/pull/54835

Need to reevaluate this issue.
